// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Balance.proto

package com.ebanking.testsystem;

public interface balanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.balanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string firstString = 1;</code>
   */
  java.lang.String getFirstString();
  /**
   * <code>string firstString = 1;</code>
   */
  com.google.protobuf.ByteString
      getFirstStringBytes();
}
