// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Balance.proto

package com.ebanking.testsystem;

public final class BalanceImpl {
  private BalanceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_balanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_balanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_balanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_balanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_balanceTransactions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_balanceTransactions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rBalance.proto\022\ntestsystem\"%\n\016balanceRe" +
      "quest\022\023\n\013firstString\030\001 \001(\t\"!\n\017balanceRes" +
      "ponse\022\016\n\006balRes\030\001 \001(\001\"=\n\023balanceTransact" +
      "ions\022\023\n\013transaction\030\002 \001(\t\022\021\n\tlastTrans\030\003" +
      " \001(\0012\244\003\n\007Balance\022J\n\016GetFirstString\022\032.tes" +
      "tsystem.balanceRequest\032\032.testsystem.bala" +
      "nceRequest\"\000\022M\n\017GetSecondString\022\032.testsy" +
      "stem.balanceRequest\032\032.testsystem.balance" +
      "Request\"\0000\001\022O\n\022GetBalanceResponse\022\032.test" +
      "system.balanceRequest\032\033.testsystem.balan" +
      "ceResponse\"\000\022R\n\025GetBalanceResponseAmt\022\032." +
      "testsystem.balanceRequest\032\033.testsystem.b" +
      "alanceResponse\"\000\022Y\n\026GetBalanceTransactio" +
      "ns\022\032.testsystem.balanceRequest\032\037.testsys" +
      "tem.balanceTransactions\"\0000\001B(\n\027com.ebank" +
      "ing.testsystemB\013BalanceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_testsystem_balanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_testsystem_balanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_balanceRequest_descriptor,
        new java.lang.String[] { "FirstString", });
    internal_static_testsystem_balanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_testsystem_balanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_balanceResponse_descriptor,
        new java.lang.String[] { "BalRes", });
    internal_static_testsystem_balanceTransactions_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_testsystem_balanceTransactions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_balanceTransactions_descriptor,
        new java.lang.String[] { "Transaction", "LastTrans", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
