// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Balance.proto

package com.ebanking.testsystem;

public interface balanceTransactionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.balanceTransactions)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transaction = 2;</code>
   */
  java.lang.String getTransaction();
  /**
   * <code>string transaction = 2;</code>
   */
  com.google.protobuf.ByteString
      getTransactionBytes();

  /**
   * <code>double lastTrans = 3;</code>
   */
  double getLastTrans();
}
