// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Balance.proto

package com.ebanking.testsystem;

public interface balanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.balanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double balRes = 1;</code>
   */
  double getBalRes();
}
