// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.ebanking.testsystem;

public interface BillPaymentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.BillPayment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bic = 1;</code>
   */
  java.lang.String getBic();
  /**
   * <code>string bic = 1;</code>
   */
  com.google.protobuf.ByteString
      getBicBytes();

  /**
   * <code>string iban = 2;</code>
   */
  java.lang.String getIban();
  /**
   * <code>string iban = 2;</code>
   */
  com.google.protobuf.ByteString
      getIbanBytes();

  /**
   * <code>string payee = 3;</code>
   */
  java.lang.String getPayee();
  /**
   * <code>string payee = 3;</code>
   */
  com.google.protobuf.ByteString
      getPayeeBytes();

  /**
   * <code>string description = 4;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>double amount = 5;</code>
   */
  double getAmount();
}
