// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.ebanking.testsystem;

public interface LoginValidationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.LoginValidation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string valid = 1;</code>
   */
  java.lang.String getValid();
  /**
   * <code>string valid = 1;</code>
   */
  com.google.protobuf.ByteString
      getValidBytes();
}
