// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.ebanking.testsystem;

public final class PaymentSystemImpl {
  private PaymentSystemImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_BillPayment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_BillPayment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_Status_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_Status_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rPayment.proto\022\ntestsystem\"\\\n\013BillPayme" +
      "nt\022\013\n\003bic\030\001 \001(\t\022\014\n\004iban\030\002 \001(\t\022\r\n\005payee\030\003" +
      " \001(\t\022\023\n\013description\030\004 \001(\t\022\016\n\006amount\030\005 \001(" +
      "\001\"\036\n\006Status\022\024\n\014confirmation\030\001 \001(\t2P\n\016Pay" +
      "mentService\022>\n\013sentPayment\022\027.testsystem." +
      "BillPayment\032\022.testsystem.Status\"\000(\001B.\n\027c" +
      "om.ebanking.testsystemB\021PaymentSystemImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_testsystem_BillPayment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_testsystem_BillPayment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_BillPayment_descriptor,
        new java.lang.String[] { "Bic", "Iban", "Payee", "Description", "Amount", });
    internal_static_testsystem_Status_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_testsystem_Status_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_Status_descriptor,
        new java.lang.String[] { "Confirmation", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
