// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trading.proto

package com.ebanking.testsystem;

public interface purchaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.purchase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string company = 2;</code>
   */
  java.lang.String getCompany();
  /**
   * <code>string company = 2;</code>
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string isin = 3;</code>
   */
  java.lang.String getIsin();
  /**
   * <code>string isin = 3;</code>
   */
  com.google.protobuf.ByteString
      getIsinBytes();

  /**
   * <code>double price = 4;</code>
   */
  double getPrice();

  /**
   * <code>int32 amount = 5;</code>
   */
  int getAmount();
}
