// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Payment.proto

package com.ebanking.testsystem;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();
}
