// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trading.proto

package com.ebanking.testsystem;

/**
 * Protobuf type {@code testsystem.stockListings}
 */
public  final class stockListings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:testsystem.stockListings)
    stockListingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stockListings.newBuilder() to construct.
  private stockListings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stockListings() {
    company_ = "";
    isin_ = "";
    price_ = 0D;
    trend_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private stockListings(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            company_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            isin_ = s;
            break;
          }
          case 25: {

            price_ = input.readDouble();
            break;
          }
          case 33: {

            trend_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ebanking.testsystem.TradingSystemImpl.internal_static_testsystem_stockListings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ebanking.testsystem.TradingSystemImpl.internal_static_testsystem_stockListings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ebanking.testsystem.stockListings.class, com.ebanking.testsystem.stockListings.Builder.class);
  }

  public static final int COMPANY_FIELD_NUMBER = 1;
  private volatile java.lang.Object company_;
  /**
   * <code>string company = 1;</code>
   */
  public java.lang.String getCompany() {
    java.lang.Object ref = company_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      company_ = s;
      return s;
    }
  }
  /**
   * <code>string company = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCompanyBytes() {
    java.lang.Object ref = company_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      company_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISIN_FIELD_NUMBER = 2;
  private volatile java.lang.Object isin_;
  /**
   * <code>string isin = 2;</code>
   */
  public java.lang.String getIsin() {
    java.lang.Object ref = isin_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isin_ = s;
      return s;
    }
  }
  /**
   * <code>string isin = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIsinBytes() {
    java.lang.Object ref = isin_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isin_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private double price_;
  /**
   * <code>double price = 3;</code>
   */
  public double getPrice() {
    return price_;
  }

  public static final int TREND_FIELD_NUMBER = 4;
  private double trend_;
  /**
   * <code>double trend = 4;</code>
   */
  public double getTrend() {
    return trend_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCompanyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, company_);
    }
    if (!getIsinBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, isin_);
    }
    if (price_ != 0D) {
      output.writeDouble(3, price_);
    }
    if (trend_ != 0D) {
      output.writeDouble(4, trend_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCompanyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, company_);
    }
    if (!getIsinBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, isin_);
    }
    if (price_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, price_);
    }
    if (trend_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, trend_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ebanking.testsystem.stockListings)) {
      return super.equals(obj);
    }
    com.ebanking.testsystem.stockListings other = (com.ebanking.testsystem.stockListings) obj;

    boolean result = true;
    result = result && getCompany()
        .equals(other.getCompany());
    result = result && getIsin()
        .equals(other.getIsin());
    result = result && (
        java.lang.Double.doubleToLongBits(getPrice())
        == java.lang.Double.doubleToLongBits(
            other.getPrice()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTrend())
        == java.lang.Double.doubleToLongBits(
            other.getTrend()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMPANY_FIELD_NUMBER;
    hash = (53 * hash) + getCompany().hashCode();
    hash = (37 * hash) + ISIN_FIELD_NUMBER;
    hash = (53 * hash) + getIsin().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPrice()));
    hash = (37 * hash) + TREND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTrend()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ebanking.testsystem.stockListings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ebanking.testsystem.stockListings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ebanking.testsystem.stockListings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ebanking.testsystem.stockListings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ebanking.testsystem.stockListings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code testsystem.stockListings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:testsystem.stockListings)
      com.ebanking.testsystem.stockListingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ebanking.testsystem.TradingSystemImpl.internal_static_testsystem_stockListings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ebanking.testsystem.TradingSystemImpl.internal_static_testsystem_stockListings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ebanking.testsystem.stockListings.class, com.ebanking.testsystem.stockListings.Builder.class);
    }

    // Construct using com.ebanking.testsystem.stockListings.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      company_ = "";

      isin_ = "";

      price_ = 0D;

      trend_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ebanking.testsystem.TradingSystemImpl.internal_static_testsystem_stockListings_descriptor;
    }

    @java.lang.Override
    public com.ebanking.testsystem.stockListings getDefaultInstanceForType() {
      return com.ebanking.testsystem.stockListings.getDefaultInstance();
    }

    @java.lang.Override
    public com.ebanking.testsystem.stockListings build() {
      com.ebanking.testsystem.stockListings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ebanking.testsystem.stockListings buildPartial() {
      com.ebanking.testsystem.stockListings result = new com.ebanking.testsystem.stockListings(this);
      result.company_ = company_;
      result.isin_ = isin_;
      result.price_ = price_;
      result.trend_ = trend_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ebanking.testsystem.stockListings) {
        return mergeFrom((com.ebanking.testsystem.stockListings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ebanking.testsystem.stockListings other) {
      if (other == com.ebanking.testsystem.stockListings.getDefaultInstance()) return this;
      if (!other.getCompany().isEmpty()) {
        company_ = other.company_;
        onChanged();
      }
      if (!other.getIsin().isEmpty()) {
        isin_ = other.isin_;
        onChanged();
      }
      if (other.getPrice() != 0D) {
        setPrice(other.getPrice());
      }
      if (other.getTrend() != 0D) {
        setTrend(other.getTrend());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ebanking.testsystem.stockListings parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ebanking.testsystem.stockListings) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object company_ = "";
    /**
     * <code>string company = 1;</code>
     */
    public java.lang.String getCompany() {
      java.lang.Object ref = company_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        company_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string company = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      java.lang.Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string company = 1;</code>
     */
    public Builder setCompany(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      company_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string company = 1;</code>
     */
    public Builder clearCompany() {
      
      company_ = getDefaultInstance().getCompany();
      onChanged();
      return this;
    }
    /**
     * <code>string company = 1;</code>
     */
    public Builder setCompanyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      company_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object isin_ = "";
    /**
     * <code>string isin = 2;</code>
     */
    public java.lang.String getIsin() {
      java.lang.Object ref = isin_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isin_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isin = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIsinBytes() {
      java.lang.Object ref = isin_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isin_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isin = 2;</code>
     */
    public Builder setIsin(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      isin_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string isin = 2;</code>
     */
    public Builder clearIsin() {
      
      isin_ = getDefaultInstance().getIsin();
      onChanged();
      return this;
    }
    /**
     * <code>string isin = 2;</code>
     */
    public Builder setIsinBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      isin_ = value;
      onChanged();
      return this;
    }

    private double price_ ;
    /**
     * <code>double price = 3;</code>
     */
    public double getPrice() {
      return price_;
    }
    /**
     * <code>double price = 3;</code>
     */
    public Builder setPrice(double value) {
      
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double price = 3;</code>
     */
    public Builder clearPrice() {
      
      price_ = 0D;
      onChanged();
      return this;
    }

    private double trend_ ;
    /**
     * <code>double trend = 4;</code>
     */
    public double getTrend() {
      return trend_;
    }
    /**
     * <code>double trend = 4;</code>
     */
    public Builder setTrend(double value) {
      
      trend_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double trend = 4;</code>
     */
    public Builder clearTrend() {
      
      trend_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:testsystem.stockListings)
  }

  // @@protoc_insertion_point(class_scope:testsystem.stockListings)
  private static final com.ebanking.testsystem.stockListings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ebanking.testsystem.stockListings();
  }

  public static com.ebanking.testsystem.stockListings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<stockListings>
      PARSER = new com.google.protobuf.AbstractParser<stockListings>() {
    @java.lang.Override
    public stockListings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stockListings(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<stockListings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stockListings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ebanking.testsystem.stockListings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

