// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trading.proto

package com.ebanking.testsystem;

public interface stockListingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:testsystem.stockListings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string company = 1;</code>
   */
  java.lang.String getCompany();
  /**
   * <code>string company = 1;</code>
   */
  com.google.protobuf.ByteString
      getCompanyBytes();

  /**
   * <code>string isin = 2;</code>
   */
  java.lang.String getIsin();
  /**
   * <code>string isin = 2;</code>
   */
  com.google.protobuf.ByteString
      getIsinBytes();

  /**
   * <code>double price = 3;</code>
   */
  double getPrice();

  /**
   * <code>double trend = 4;</code>
   */
  double getTrend();
}
