// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trading.proto

package com.ebanking.testsystem;

public final class TradingSystemImpl {
  private TradingSystemImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_purchase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_purchase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_testsystem_stockListings_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_testsystem_stockListings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTrading.proto\022\ntestsystem\"Y\n\010purchase\022" +
      "\017\n\007request\030\001 \001(\t\022\017\n\007company\030\002 \001(\t\022\014\n\004isi" +
      "n\030\003 \001(\t\022\r\n\005price\030\004 \001(\001\022\016\n\006amount\030\005 \001(\005\"L" +
      "\n\rstockListings\022\017\n\007company\030\001 \001(\t\022\014\n\004isin" +
      "\030\002 \001(\t\022\r\n\005price\030\003 \001(\001\022\r\n\005trend\030\004 \001(\0012X\n\007" +
      "Trading\022M\n\024bidirectStartTrading\022\024.testsy" +
      "stem.purchase\032\031.testsystem.stockListings" +
      "\"\000(\0010\001B.\n\027com.ebanking.testsystemB\021Tradi" +
      "ngSystemImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_testsystem_purchase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_testsystem_purchase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_purchase_descriptor,
        new java.lang.String[] { "Request", "Company", "Isin", "Price", "Amount", });
    internal_static_testsystem_stockListings_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_testsystem_stockListings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_testsystem_stockListings_descriptor,
        new java.lang.String[] { "Company", "Isin", "Price", "Trend", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
